### ISSUE TITLE
Twig 3.12.0 possible compatibility issue

### ISSUE THREAD

**Issue by xvilo** [sserbin/twig-linter#51]
In some of our templates we check if a twig `block` is defined. An example of this would be:
```twig
{% if block('possiblyDoesNotExist') is defined %}
    <div>
        {{ block('possiblyDoesNotExist')|raw }}
    </div>
{% endif %}
```

We use `sserbin/twig-linter` in our composer package that exposes common templates and embeds for use in (Symfony) PHP Projects and where we would like to automatically check the twig syntax. 

With the latest version of this package and `twig/twig` 3.12.0 the following code does now produce errors:
```
$ vendor/bin/twig-linter lint templates
  ERROR  in templates/index.html.twig (line 1)
  >>  1      {% if block('possiblyDoesNotExist') is defined %}
  >> The "defined" test only works with simple variables. 
      2          <div>
      3              {{ block('possiblyDoesNotExist')|raw }}
```

While, when rendering the template, this logic is accepted just fine with twig. Is this a bug in the linter code, or is there happening something else?

For your convenience, here is a repository with some examples in which you should be able to reproduce the issue. For crude instructions on how to get it running, please refer to its README: https://github.com/xvilo/tests/tree/main/2024-08-29-twig-define-3.12.0

**Comment by sserbin** [comment]
hey Sem, thanks for the detailed writeup, I think I got this fixed and published a new release https://github.com/sserbin/twig-linter/releases/tag/3.1.1 
Let me know if you'd still run into issues :+1:
