### ISSUE TITLE
Custom stubs

### ISSUE THREAD

**Issue by roanmeijerpixel** [sserbin/twig-linter#52]
Is it possible to add a custom stub to the linter?
I have developed an own switch block for twig but the linter gives an error for the switch block.

**Comment by sserbin** [comment]
hey @roanmeijerpixel yeah that's possible - see https://github.com/sserbin/twig-linter?tab=readme-ov-file#limitationsknown-issues also see similar question here https://github.com/sserbin/twig-linter/issues/11

**Comment by roanmeijerpixel** [comment]
@sserbin Is it also possible if im using the linter with composer? And i use the linter with timber, i dont know if that makes a difference?
