### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by xvilo** [sserbin/twig-linter#9]
Hi @sserbin,

I know this might be a spam issue, however, I would like to contribute some more changes to this project for my [hacktoberfest ](https://hacktoberfest.digitalocean.com) goal. However, this year the rules are changed and maintainers must enlist their repositories manually. 

Would you be so kind doing so before Oct 30th? The repository should have a `hacktoberfest ` topic as per the instructions on https://hacktoberfest.digitalocean.com/hacktoberfest-update

Sorry again, and thanks in advance!

**Comment by sserbin** [comment]
Sure thing @xvilo , added the topic now. Thanks for contributing :+1:
